#!/usr/bin/env python3
"""Generates Claude Code and Codex agent files from the shared charters.

Charters in ``agents/`` name a tier, and ``tiers.json`` maps each tier to a
model per harness, so switching providers means editing one file. Each
agent's ``memory/<name>.md`` is inlined at sync time so agents spend no tool
call reading it. Every generated file carries ``GENERATED_MARKER``; the sync
only replaces or removes files that carry it, so hand-written agents in the
same directories are safe.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import NamedTuple

GENERATED_MARKER = "Generated by ~/.config/agents/sync.py; edit the charter instead."
SOURCE_DIR = Path(__file__).resolve().parent
DEFAULT_CLAUDE_DIR = Path.home() / ".claude" / "agents"
DEFAULT_CODEX_DIR = Path.home() / ".codex" / "agents"

KNOWN_TOOLS = frozenset(
    {"Read", "Grep", "Glob", "Bash", "Edit", "Write", "Agent", "Skill", "WebSearch", "WebFetch"}
)
CODEX_SANDBOX_MODES = frozenset({"read-only", "workspace-write"})
CHARTER_FIELDS = frozenset({"name", "tier", "description", "tools", "codex_sandbox"})
REQUIRED_CHARTER_FIELDS = ("name", "tier", "description", "tools")
HARNESSES = ("claude", "codex")


class ConfigError(Exception):
    """Raised when a charter, the tier map, or an output directory is invalid."""


class HarnessModel(NamedTuple):
    model: str | None
    effort: str | None


class Tier(NamedTuple):
    claude: HarnessModel
    codex: HarnessModel


class Charter(NamedTuple):
    name: str
    tier: str
    description: str
    tools: tuple[str, ...]
    codex_sandbox: str | None
    body: str


class Preambles(NamedTuple):
    shared: str
    codex: str


class AgentSource(NamedTuple):
    charter: Charter
    memory: str


class Change(NamedTuple):
    path: Path
    action: str  # "write" or "remove"


def _parse_harness_model(raw: object, where: str) -> HarnessModel:
    if not isinstance(raw, Mapping) or set(raw) != {"model", "effort"}:
        raise ConfigError(f"{where}: expected an object with exactly 'model' and 'effort'")
    model, effort = raw["model"], raw["effort"]
    for key, value in (("model", model), ("effort", effort)):
        if value is not None and not isinstance(value, str):
            raise ConfigError(f"{where}.{key}: expected a string or null")
    return HarnessModel(model=model, effort=effort)


def parse_tiers(text: str) -> dict[str, Tier]:
    raw = json.loads(text)
    if not isinstance(raw, Mapping):
        raise ConfigError("tiers.json: expected an object of tiers")
    tiers: dict[str, Tier] = {}
    for tier_name, harness_map in raw.items():
        if not isinstance(harness_map, Mapping) or set(harness_map) != set(HARNESSES):
            raise ConfigError(f"tiers.json: tier '{tier_name}' must define exactly {HARNESSES}")
        claude = _parse_harness_model(harness_map["claude"], f"{tier_name}.claude")
        if claude.model is None:
            raise ConfigError(f"tiers.json: {tier_name}.claude.model is required")
        codex = _parse_harness_model(harness_map["codex"], f"{tier_name}.codex")
        tiers[tier_name] = Tier(claude=claude, codex=codex)
    return tiers


def _parse_frontmatter_value(raw_value: str, where: str) -> str:
    if not raw_value.startswith('"'):
        return raw_value
    value = json.loads(raw_value)
    if not isinstance(value, str):
        raise ConfigError(f"{where}: quoted value must be a string")
    return value


def parse_charter(text: str, path: Path) -> Charter:
    if not text.startswith("---\n"):
        raise ConfigError(f"{path}: missing frontmatter")
    frontmatter_end = text.find("\n---\n", 4)
    if frontmatter_end == -1:
        raise ConfigError(f"{path}: unterminated frontmatter")

    fields: dict[str, str] = {}
    for line in text[4:frontmatter_end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, raw_value = line.partition(": ")
        if not separator or key not in CHARTER_FIELDS:
            raise ConfigError(f"{path}: unexpected frontmatter line {line!r}")
        fields[key] = _parse_frontmatter_value(raw_value.strip(), f"{path}:{key}")

    missing = [field for field in REQUIRED_CHARTER_FIELDS if field not in fields]
    if missing:
        raise ConfigError(f"{path}: missing frontmatter fields {missing}")
    if fields["name"] != path.stem:
        raise ConfigError(f"{path}: name '{fields['name']}' must match the file name")

    tools = tuple(tool.strip() for tool in fields["tools"].split(","))
    unknown_tools = sorted(set(tools) - KNOWN_TOOLS)
    if unknown_tools:
        raise ConfigError(f"{path}: unknown tools {unknown_tools}")

    codex_sandbox = fields.get("codex_sandbox")
    if codex_sandbox is not None and codex_sandbox not in CODEX_SANDBOX_MODES:
        raise ConfigError(f"{path}: codex_sandbox must be one of {sorted(CODEX_SANDBOX_MODES)}")

    return Charter(
        name=fields["name"],
        tier=fields["tier"],
        description=fields["description"],
        tools=tools,
        codex_sandbox=codex_sandbox,
        body=text[frontmatter_end + len("\n---\n") :].strip(),
    )


def load_charters(source_dir: Path, tiers: Mapping[str, Tier]) -> list[Charter]:
    charters = [
        parse_charter(path.read_text(), path) for path in sorted((source_dir / "agents").glob("*.md"))
    ]
    for charter in charters:
        if charter.tier not in tiers:
            raise ConfigError(f"{charter.name}: unknown tier '{charter.tier}'")
    return charters


def _instructions(source: AgentSource, preamble: str) -> str:
    sections = [source.charter.body, preamble.strip()]
    if source.memory:
        sections.append(f"## Memory\n\n{source.memory}")
    return "\n\n".join(sections) + "\n"


def render_claude(source: AgentSource, tier: Tier, preambles: Preambles) -> str:
    charter = source.charter
    lines = [
        "---",
        f"# {GENERATED_MARKER}",
        f"name: {charter.name}",
        f"description: {json.dumps(charter.description, ensure_ascii=False)}",
        f"model: {tier.claude.model}",
    ]
    if tier.claude.effort is not None:
        lines.append(f"effort: {tier.claude.effort}")
    lines += [f"tools: {', '.join(charter.tools)}", "---", ""]
    return "\n".join(lines) + _instructions(source, preambles.shared)


def _toml_string(value: str) -> str:
    # JSON string escapes are a subset of TOML basic-string escapes.
    return json.dumps(value, ensure_ascii=False)


def _toml_multiline_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return f'"""\n{escaped}"""'


def render_codex(source: AgentSource, tier: Tier, preambles: Preambles) -> str:
    charter = source.charter
    # Codex does not enforce a tool allowlist, so it becomes a stated rule.
    tool_rule = f"Allowed tools: {', '.join(charter.tools)}. Use no others."
    preamble = "\n\n".join((preambles.shared.strip(), preambles.codex.strip(), tool_rule))
    lines = [
        f"# {GENERATED_MARKER}",
        f"name = {_toml_string(charter.name)}",
        f"description = {_toml_string(charter.description)}",
    ]
    if tier.codex.model is not None:
        lines.append(f"model = {_toml_string(tier.codex.model)}")
    if tier.codex.effort is not None:
        lines.append(f"model_reasoning_effort = {_toml_string(tier.codex.effort)}")
    if charter.codex_sandbox is not None:
        lines.append(f"sandbox_mode = {_toml_string(charter.codex_sandbox)}")
    lines.append(f"developer_instructions = {_toml_multiline_string(_instructions(source, preamble))}")
    return "\n".join(lines) + "\n"


def desired_outputs(source_dir: Path, claude_dir: Path, codex_dir: Path) -> dict[Path, str]:
    tiers = parse_tiers((source_dir / "tiers.json").read_text())
    preambles = Preambles(
        shared=(source_dir / "preamble.md").read_text(),
        codex=(source_dir / "codex-preamble.md").read_text(),
    )
    outputs: dict[Path, str] = {}
    for charter in load_charters(source_dir, tiers):
        memory_path = source_dir / "memory" / f"{charter.name}.md"
        memory = memory_path.read_text().strip() if memory_path.exists() else ""
        source = AgentSource(charter=charter, memory=memory)
        tier = tiers[charter.tier]
        outputs[claude_dir / f"{charter.name}.md"] = render_claude(source, tier, preambles)
        outputs[codex_dir / f"{charter.name}.toml"] = render_codex(source, tier, preambles)
    return outputs


def _is_generated(path: Path) -> bool:
    return GENERATED_MARKER in path.read_text()


def plan_changes(
    outputs: Mapping[Path, str], claude_dir: Path, codex_dir: Path
) -> list[Change]:
    changes: list[Change] = []
    for path, content in sorted(outputs.items()):
        if not path.exists():
            changes.append(Change(path, "write"))
        elif not _is_generated(path):
            raise ConfigError(f"{path} exists and was not generated by sync.py; move it aside first")
        elif path.read_text() != content:
            changes.append(Change(path, "write"))

    for directory, suffix in ((claude_dir, ".md"), (codex_dir, ".toml")):
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob(f"*{suffix}")):
            if path not in outputs and _is_generated(path):
                changes.append(Change(path, "remove"))
    return changes


def apply_changes(changes: Sequence[Change], outputs: Mapping[Path, str]) -> None:
    for change in changes:
        if change.action == "remove":
            change.path.unlink()
        else:
            change.path.parent.mkdir(parents=True, exist_ok=True)
            change.path.write_text(outputs[change.path])


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift without writing; exit 1 on drift")
    parser.add_argument("--source-dir", type=Path, default=SOURCE_DIR)
    parser.add_argument("--claude-dir", type=Path, default=DEFAULT_CLAUDE_DIR)
    parser.add_argument("--codex-dir", type=Path, default=DEFAULT_CODEX_DIR)
    args = parser.parse_args(argv)

    try:
        outputs = desired_outputs(args.source_dir, args.claude_dir, args.codex_dir)
        changes = plan_changes(outputs, args.claude_dir, args.codex_dir)
    except (ConfigError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    for change in changes:
        print(f"{'would ' if args.check else ''}{change.action}: {change.path}")
    if args.check:
        return 1 if changes else 0
    apply_changes(changes, outputs)
    if not changes:
        print("up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
